apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-measure
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: rpi-measure
  template:
    metadata:
      labels:
        app: rpi-measure
    spec:
      containers:
      - image: alkolhar/rpi-measure:latest
        name: rpi-measure
        ports:
        - containerPort: 8080
---
# Service YAML definition
apiVersion: v1
kind: Service
metadata:
  name: rpi-measure
spec:
  selector:
      app: rpi-measure
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
